language: python

notifications:
  slack:
    rooms:
      - travelio-hq:qIQfZYNc1djrZqPWtB039ym5
    on_success: never
    on_failure: always

python:
    - 3.7

before_install:
  - chmod +x build.sh

install:
  - pip install -r requirements.txt

services:
  - docker

script:
  - ./build.sh --ci